Revert "gcc: Fix style for Linuxbrew"
This reverts commit d1d40b2a4a0ab7607d4dc4c449f14208d4916608.

FileUtils.mv fails with Ruby 1.9.3 on Docker.
Error: No such file or directory -
/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/lib64/libtsan.so.0